avatar component
Sandesh9834/component-library pull request #4
Opened 2022-02-21 09:00 UTC by Sandesh9834

![image](https://user-images.githubusercontent.com/78275234/154921953-53bf5482-4e37-4aa2-90ae-d87d71792a99.png)

2022-02-21 15:57 UTC, iHarryD approved these changes
Looks good. You can merge.

2022-02-22 03:46 UTC, Vivek-jpg requested changes
use em or rem in px rest can be merged

2022-02-22 03:46 UTC, Vivek-jpg commented on Components/avatar/avatar.css
> +      flex-direction: row;
use rem and flex by default use raw so don't need to define raw

2022-02-22 03:46 UTC, Vivek-jpg commented on Components/avatar/avatar.css
> +      gap: 25px;
use rem here as well

2022-02-22 03:46 UTC, Vivek-jpg commented on Components/avatar/avatar.css
> +  .medium{
use rem

2022-02-22 03:46 UTC, Vivek-jpg commented on Components/avatar/avatar.html
> +                      <img class="avatar-square square-large" src="Profile_avatar_placeholder_large.png" alt="">
naming are good

2022-02-22 03:46 UTC, Vivek-jpg commented on Components/avatar/avatar.html
> +                  <h3>Oval Avatar</h3>
put image in a image folder

2022-02-22 04:00 UTC, merged